// frontend/src/components/Editor.tsx
import React, { useEffect, useRef, useState } from 'react';
import { useSyncedStore } from '@syncedstore/react';
import { EditorState } from '@codemirror/state';
import { EditorView, keymap, lineNumbers, highlightActiveLineGutter, highlightSpecialChars } from '@codemirror/view';
import { javascript } from '@codemirror/lang-javascript';
import { defaultKeymap, indentWithTab } from '@codemirror/commands';
import { tags } from '@lezer/highlight';
import { HighlightStyle, indentOnInput, bracketMatching, foldGutter, foldKeymap, syntaxHighlighting, defaultHighlightStyle } from '@codemirror/language';
import { autocompletion, completionKeymap, closeBrackets, closeBracketsKeymap } from '@codemirror/autocomplete';
import { lintKeymap } from '@codemirror/lint';
import { yCollab } from 'y-codemirror.next';
import { store, yText, awareness, AwarenessState } from '../store';
import * as Y from 'yjs';
import { UndoManager } from 'yjs';
import './Editor.css';

const Editor: React.FC = () => {
    const editorRef = useRef<HTMLDivElement>(null);
    const [userInfo, setUserInfo] = useState<AwarenessState['user'] | null>(null);
    const [otherOnlineUsers, setOtherOnlineUsers] = useState<AwarenessState['user'][]>([]);
    const [showOnlineUsersList, setShowOnlineUsersList] = useState(false);
    const state = useSyncedStore(store);


    useEffect(() => {
        if (!yText) return;

        const undoManager = new UndoManager(yText as Y.Text);

        const onAwarenessChange = () => {
            const currentUser = awareness.getLocalState()?.user || null;
            setUserInfo(currentUser);
            const states = Array.from(awareness.getStates().values());
            const otherUsers = states
                .map(state => state.user)
                .filter(user => !!user && user.name !== currentUser?.name);
            setOtherOnlineUsers(otherUsers);
        };

        awareness.on('change', onAwarenessChange);
        // Set initial state
        onAwarenessChange();


        const syntaxStyles = HighlightStyle.define([
            { tag: tags.keyword, color: '#0000ff', fontWeight: 'bold' },
            { tag: tags.comment, color: '#008000', fontStyle: 'italic' },
            { tag: tags.string, color: '#a31515' },
            { tag: tags.number, color: '#098658' },
            { tag: tags.operator, color: '#000000' },
            { tag: tags.variableName, color: '#001080' },
            { tag: tags.propertyName, color: '#001080' },
            { tag: tags.function(tags.variableName), color: '#795E26' },
            { tag: tags.definition(tags.propertyName), color: '#001080' },
        ]);

        const editorState = EditorState.create({
            doc: yText.toString(),
            extensions: [
                lineNumbers(),
                highlightActiveLineGutter(),
                highlightSpecialChars(),
                foldGutter(),
                indentOnInput(),
                bracketMatching(),
                closeBrackets(),
                autocompletion(),
                javascript(),
                syntaxHighlighting(defaultHighlightStyle, { fallback: true }),
                syntaxHighlighting(syntaxStyles),
                yCollab(yText as Y.Text, awareness, { undoManager }),
                EditorView.theme({
                    '&': { height: '100%' },
                    '.cm-content': {
                        fontSize: '20px',
                        paddingTop: '16px',
                    },
                    '.cm-scroller': {
                        fontFamily: "'Consolas', 'Monaco', 'Courier New', monospace",
                        fontSize: '14px',
                        lineHeight: '1.5',
                    },
                }),
                EditorView.lineWrapping,
                EditorState.tabSize.of(2),
                keymap.of([
                    ...defaultKeymap,
                    ...foldKeymap,
                    ...completionKeymap,
                    ...closeBracketsKeymap,
                    ...lintKeymap,
                    indentWithTab,
                    {
                        key: 'Mod-z',
                        run: () => {
                            undoManager.undo();
                            return true;
                        },
                    },
                    {
                        key: 'Mod-y',
                        run: () => {
                            undoManager.redo();
                            return true;
                        },
                    },
                    {
                        key: 'Mod-Shift-z',
                        run: () => {
                            undoManager.redo();
                            return true;
                        },
                    },
                ]),
            ],
        });

        const view = new EditorView({
            state: editorState,
            parent: editorRef.current!,
        });

        return () => {
            awareness.off('change', onAwarenessChange);
            view.destroy();
        };
    }, [yText]);

    const toggleOnlineUsersList = () => {
        setShowOnlineUsersList(prev => !prev);
    };

    if (!state) {
        return <div>Loading...</div>
    }

    return (
        <div className="editor-container">
            <div className="doc-actions">
                {userInfo && (
                    <div>
                        <span>You: </span>
                        <span style={{ backgroundColor: userInfo.color }}>{userInfo.name}</span>
                    </div>
                )}
            </div>
            <div className="toolbar">
                <select>
                    <option value="javascript">JavaScript</option>
                </select>
            </div>
            <div ref={editorRef} className="code-editor"></div>
            <button onClick={toggleOnlineUsersList} className="toggle-users-button">
                {showOnlineUsersList ? 'Hide' : 'Show'} online users
            </button>
            {showOnlineUsersList && (
                <ol>
                    {otherOnlineUsers.map(user => (
                         <li key={user.name}>
                            <span style={{ backgroundColor: user.color }}>{user.name}</span>
                        </li>
                    ))}
                </ol>
            )}
        </div>
    );
};

export default Editor;

// frontend/src/app/components/editor/editor.component.ts
import { Component, AfterViewInit, ElementRef, ViewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { WebsocketService } from '../../services/websocket.service';
import * as Y from 'yjs';
import { EditorState } from '@codemirror/state';
import { EditorView, keymap, lineNumbers, highlightActiveLineGutter, highlightSpecialChars } from '@codemirror/view';
import { javascript } from '@codemirror/lang-javascript';
import { defaultKeymap, history, historyKeymap, indentWithTab } from '@codemirror/commands';
import { tags } from '@lezer/highlight';
import {
  HighlightStyle,
  defaultHighlightStyle,
  indentOnInput,
  bracketMatching,
  foldGutter,
  foldKeymap,
  syntaxHighlighting
} from '@codemirror/language';
import { autocompletion, completionKeymap, closeBrackets, closeBracketsKeymap } from '@codemirror/autocomplete';
import { lintKeymap } from '@codemirror/lint';
import { yCollab } from 'y-codemirror.next'

@Component({
  selector: 'app-editor',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './editor.component.html',
  styleUrls: ['./editor.component.scss']
})
export class EditorComponent implements AfterViewInit {
  @ViewChild('editorContainer') editorContainer!: ElementRef;
  private ytext: Y.Text;
  private editorView?: EditorView;
  selectedLanguage = 'javascript';
  userInfo: Record<string, any> | null = null;
  otherOnlineUsers: Record<string, any>[] = [];
  showOnlineUsersList = false;

  constructor(private wsService: WebsocketService) {
    this.ytext = this.wsService.getDoc().getText('collaborative-editor');
    this.userInfo = this.wsService.getProvider().awareness.getLocalState()?.['user'];
    this.wsService.getProvider().awareness.on('change', () => {
      const states = [...this.wsService.getProvider().awareness.getStates().values()];
      this.otherOnlineUsers = states
        .map(state => state['user'])
        .filter(user => !!user && user['name'] !== this.userInfo?.['name']);
    });
  }

  ngAfterViewInit() {
    if (this.editorContainer?.nativeElement) {
      this.initializeEditor();
    }
  }

  toggleOnlineUsersList() {
    this.showOnlineUsersList = !this.showOnlineUsersList;
  }

  private initializeEditor() {
    const syntaxStyles = HighlightStyle.define([
      { tag: tags.keyword, color: "#0000ff", fontWeight: "bold" },
      { tag: tags.comment, color: "#008000", fontStyle: "italic" },
      { tag: tags.string, color: "#a31515" },
      { tag: tags.number, color: "#098658" },
      { tag: tags.operator, color: "#000000" },
      { tag: tags.variableName, color: "#001080" },
      { tag: tags.propertyName, color: "#001080" },
      { tag: tags.function(tags.variableName), color: "#795E26" },
      { tag: tags.definition(tags.propertyName), color: "#001080" }
    ]);

    const state = EditorState.create({
      doc: this.ytext.toString(),
      extensions: [
        lineNumbers(),
        highlightActiveLineGutter(),
        highlightSpecialChars(),
        history(),
        foldGutter(),
        indentOnInput(),
        bracketMatching(),
        closeBrackets(),
        autocompletion(),
        this.getLanguageExtension(),
        syntaxHighlighting(defaultHighlightStyle, { fallback: true }),
        syntaxHighlighting(syntaxStyles),
        yCollab(this.ytext, this.wsService.getProvider().awareness),
        EditorView.theme({
          "&": { height: "100%" },
          ".cm-content": {
            fontSize: "20px",
            paddingTop: "16px"
          },
          ".cm-scroller": {
            fontFamily: "'Consolas', 'Monaco', 'Courier New', monospace",
            fontSize: "14px",
            lineHeight: "1.5"
          }
        }),
        EditorView.lineWrapping,
        EditorState.tabSize.of(2),
        keymap.of([
          ...defaultKeymap,
          ...historyKeymap,
          ...foldKeymap,
          ...completionKeymap,
          ...closeBracketsKeymap,
          ...lintKeymap,
          indentWithTab
        ]),
      ]
    });

    this.editorView = new EditorView({
      state,
      parent: this.editorContainer.nativeElement
    });
  }

  private getLanguageExtension() {
    switch (this.selectedLanguage) {
      case 'javascript':
        return javascript({ jsx: false });
      case 'typescript':
        return javascript({ typescript: true });
      default:
        return javascript();
    }
  }

  onLanguageChange() {
    if (this.editorView) {
      const content = this.editorView.state.doc.toString();
      this.editorView.destroy();
      this.initializeEditor();
    }
  }
}

<div class="editor-container">
  <div class="doc-actions">
    @if (userInfo) {
      <div>
        <span>You: </span>
        <span [style.backgroundColor]="userInfo['color']">{{ userInfo['name'] }}</span>
      </div>
    }
  </div>
  <div class="toolbar">
    <select [(ngModel)]="selectedLanguage" (change)="onLanguageChange()">
      <option value="javascript">JavaScript</option>
      <option value="typescript">TypeScript</option>
    </select>
  </div>
  <div #editorContainer class="code-editor"></div>
  <button (click)="toggleOnlineUsersList()" class="toggle-users-button">
    {{ showOnlineUsersList ? 'Hide' : 'Show'}} online users
  </button>
  <ol [style.display]="showOnlineUsersList ? 'block' : 'none'">
    @for (user of otherOnlineUsers; track user['name']) {
      <li>
        <span [style.backgroundColor]="user['color']">{{ user['name'] }}</span>
      </li>
    }
  </ol>
</div>
